### ISSUE TITLE
Polluting home directory

### ISSUE THREAD

**Issue by ewels** [s-andrews/BamQC#12]
So it looks like BamQC makes `bamqc_prefs.txt` and `BamQC_files` in the user's home directory by default. This is a bit of a pet hate of mine - I try to keep my home directory pretty well organised so don't like it when programs create stuff there without asking me.

Suggestions:
- Put everything in a directory called `.bamqc` instead, so it's hidden
- Prompt for file locations instead of assuming a default
- Mac OSX only - use a `BamQC` directory inside `~/Library` (typical place for such files).

Feel free to tell me that I can change the file locations myself and I should stop being so OCD :grin:

**Comment by pdp10** [comment]
Thanks for your comment :)
- bamqc_pref.txt could be put into a hidden folder (e.g. .bamqc) 
- Not sure about BamQC_files though as these contain the downloaded genomes and if someone wants to get rid of them, s/he must know that they are inside a hidden folder. This is an obvious place for programmers or Linux users but not necessarily for other people.

**Comment by s-andrews** [comment]
I'd suggest leaving the bamqc_prefs.txt where it is, simply because it's now effectively an editable conf file.  The genomes folder can go wherever you like, but you'd need to edit the value in the conf file so the program knows where to look.  I don't think this is documented yet so we should probably do that.

Would it seem petty to point out that clusterflow puts a non hidden folder into the user's home directory :-)

**Comment by ewels** [comment]
Which version of Cluster Flow are you guys using? I think [you'll find](https://github.com/ewels/clusterflow/blob/master/source/CF/Constants.pm#L89) that it's now called `~/.clusterflow` which should be hidden  :wink: 

Is there a cross-platform method of accessing `~/Library` or it's other OS equivalents? This seems tidier to me than using the root level user directory.

**Comment by pdp10** [comment]
Okay I put the bamqc_prefs.txt back where it was and left the rest in the hidden folder.
